version: "3"
services:
  frontend:
    image: jpyles0524/dev_site
    build:
      context: ./
      args:
        - DOPPLER_TOKEN=${DOPPLER_TOKEN}
    container_name: portfolio
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
    networks:
      - webservice-network
      - vsn
networks:
  webservice-network:
    external:
      name: webservice-network
  vsn:
    external:
      name: vsn
