services:
  frontend:
    image: jpyles0524/dev_site:latest
    ports:
      - 3000:3000
    build:
      context: ./
      args:
        DOPPLER_TOKEN: ${DOPPLER_TOKEN}
        MONGO_URI: ${MONGO_URI}
    container_name: portfolio
    command: doppler run -t $DOPPLER_TOKEN -- npm run start
    env_file: .env
    environment:
      DOPPLER_TOKEN: ${DOPPLER_TOKEN}
