version: "3"
services:
  frontend:
    build:
      context: ./
    container_name: portfolio
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
    ports:
      - "3000:3000"
    networks:
      - webservice-network

networks:
  webservice-network:
    external:
      name: webservice-network
