version: "3"
services:
  frontend:
    image: jpyles0524/dev_site
    build:
      context: ./
      args:
        - DOPPLER_TOKEN=${DOPPLER_TOKEN}
    container_name: portfolio
    command: pdm run python -m uvicorn api.backend.app:app --reload --host 0.0.0.0 --port 8000,
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
    networks:
      - webservice-network
networks:
  webservice-network:
    external:
      name: webservice-network
