version: "3"
services:
  frontend:
    image: jpyles0524/dev_site
    ports:
      - 3000:3000
    build:
      context: ./
      args:
        NEXT_PUBLIC_DISCORD_USER_ID: ${NEXT_PUBLIC_DISCORD_USER_ID}
        NEXT_PUBLIC_SPOTIFY_CLIENT_ID: ${NEXT_PUBLIC_SPOTIFY_CLIENT_ID}
        NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET: ${NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET}
        NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN: ${NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN}
    container_name: portfolio
    command: npm run start
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_DISCORD_USER_ID: ${NEXT_PUBLIC_DISCORD_USER_ID}
      NEXT_PUBLIC_SPOTIFY_CLIENT_ID: ${NEXT_PUBLIC_SPOTIFY_CLIENT_ID}
      NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET: ${NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET}
      NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN: ${NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN}
    networks:
      - webservice-network
networks:
  webservice-network:
    external:
      name: webservice-network
