services:
  frontend:
    image: jpyles0524/dev_site:latest
    ports:
      - 3000:3000
    build:
      context: ./
      args:
        DOPPLER_TOKEN: ${DOPPLER_TOKEN}
        NEXT_PUBLIC_DISCORD_USER_ID: ${NEXT_PUBLIC_DISCORD_USER_ID}
        NEXT_PUBLIC_SPOTIFY_CLIENT_ID: ${NEXT_PUBLIC_SPOTIFY_CLIENT_ID}
        NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET: ${NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET}
        NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN: ${NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: portfolio
    command: doppler run -t $DOPPLER_TOKEN -- npm run start
    env_file: .env
    environment:
      DOPPLER_TOKEN: ${DOPPLER_TOKEN}
      NEXT_PUBLIC_DISCORD_USER_ID: ${NEXT_PUBLIC_DISCORD_USER_ID}
      NEXT_PUBLIC_SPOTIFY_CLIENT_ID: ${NEXT_PUBLIC_SPOTIFY_CLIENT_ID}
      NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET: ${NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET}
      NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN: ${NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    networks:
      - webservice-network
networks:
  webservice-network:
    external:
      name: webservice-network
