FROM node:21
WORKDIR /app

COPY package*.json ./

RUN npm install

COPY public /app/public
COPY src /app/src
COPY tsconfig.json /app/tsconfig.json
COPY tailwind.config.js /app/tailwind.config.js
COPY babel.config.js /app/babel.config.js
COPY next.config.mjs /app/next.config.mjs
COPY postcss.config.js /app/postcss.config.js

ARG NEXT_PUBLIC_DISCORD_USER_ID
ARG NEXT_PUBLIC_SPOTIFY_CLIENT_ID
ARG NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET
ARG NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN

ENV NEXT_PUBLIC_DISCORD_USER_ID=${NEXT_PUBLIC_DISCORD_USER_ID}
ENV NEXT_PUBLIC_SPOTIFY_CLIENT_ID=${NEXT_PUBLIC_SPOTIFY_CLIENT_ID}
ENV NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET=${NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET}
ENV NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN=${NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN}

RUN npm run build
