apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-site
  namespace: argocd
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jaypyles/Developer-Site
    path: charts/dev-site/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true