apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-site
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/arthurk/argocd-example-install.git
    path: charts/dev-site/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true