apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: portfolio-doppler-secret
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
  managedSecret:
    name: portfolio-doppler-secret
    namespace: default
    type: Opaque
