apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.metadata.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  revisionHistoryLimit: {{ .Values.app.revisionHistoryLimit }}
  selector:
    matchLabels:
      name: {{ .Values.app.metadata.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.app.metadata.name }}
    spec:
      containers:
        - args:
            - npm
            - run
            - start
          image: {{ .Values.app.image }}:{{ .Values.app.APP_VERSION }}
          name: {{ .Values.app.name }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Values.doppler.secret }}
      restartPolicy: Always
