apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
        - args:
            - npm
            - run
            - start
          image: jpyles0524/dev_site:{{ .Values.env.APP_VERSION }}
          name: portfolio
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                secretKeyRef:
                  name: portfolio-doppler-secret
                  key: NEXT_PUBLIC_API_URL
            - name: NEXT_PUBLIC_DISCORD_USER_ID
              valueFrom:
                secretKeyRef:
                  name: portfolio-doppler-secret
                  key: NEXT_PUBLIC_DISCORD_USER_ID
            - name: NEXT_PUBLIC_SPOTIFY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: portfolio-doppler-secret
                  key: NEXT_PUBLIC_SPOTIFY_CLIENT_ID
            - name: NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: portfolio-doppler-secret
                  key: NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET
            - name: NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: portfolio-doppler-secret
                  key: NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN
      restartPolicy: Always
