apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  NEXT_PUBLIC_DISCORD_USER_ID: "$NEXT_PUBLIC_DISCORD_USER_ID"
  NEXT_PUBLIC_SPOTIFY_CLIENT_ID: "$NEXT_PUBLIC_SPOTIFY_CLIENT_ID"
  NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET: "$NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET"
  NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN: "$NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN"
  NEXT_PUBLIC_API_URL: "$NEXT_PUBLIC_API_URL"
