apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
        - args:
            - npm
            - run
            - start
          env:
            - name: NEXT_PUBLIC_API_URL
            - name: NEXT_PUBLIC_DISCORD_USER_ID
            - name: NEXT_PUBLIC_SPOTIFY_CLIENT_ID
            - name: NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET
            - name: NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN
          image: jpyles0524/dev_site-${BRANCH_NAME}:{{ .Value.env.APP_VERSION }}
          name: portfolio
          imagePullPolicy: Always 
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: frontend-configmap
      restartPolicy: Always
