apiVersion: v1
kind: Service
metadata:
  labels:
  name: frontend
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 32000
  selector:
    name: frontend
  type: NodePort
