app:
  APP_VERSION: 1.3.1
  replicas: 2
  revisionHistoryLimit: 1
  metadata:
    name: frontend
  name: portfolio
  image: jpyles0524/dev_site

doppler:
  secret: portfolio-doppler-secret
  tokenSecret: doppler-token-secret
  namespace: doppler-operator-system

env: [
  "NEXT_PUBLIC_API_URL",
  "NEXT_PUBLIC_DISCORD_USER_ID",
  "NEXT_PUBLIC_SPOTIFY_CLIENT_ID",
  "NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET",
  "NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN",
  "NEXT_PUBLIC_BASE_URL",
  "MONGO_URI",
]
