app:
  APP_VERSION: 1.4.5
  replicas: 2
  revisionHistoryLimit: 1
  metadata:
    name: frontend
  name: portfolio
  image: jpyles0524/dev_site

doppler:
  secret: portfolio-doppler-secret
  tokenSecret: doppler-token-secret
  namespace: doppler-operator-system