name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GPAT_TOKEN }}

      - name: Setup helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/dev_site:${{ github.event.workflow_run.head_branch || github.ref_name }}-${{steps.vars.outputs.sha_short}}
      #     build-args: |
      #       NEXT_PUBLIC_DISCORD_USER_ID=${{ secrets.NEXT_PUBLIC_DISCORD_USER_ID }}
      #       NEXT_PUBLIC_SPOTIFY_CLIENT_ID=${{ secrets.NEXT_PUBLIC_SPOTIFY_CLIENT_ID }}
      #       NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET=${{ secrets.NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET }}
      #       NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN=${{ secrets.NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN }}
      #       NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: Package Helm Chart
        run: |
          helm package ./charts/dev-site
          mkdir -p artifacts
          mv *.tgz artifacts/

      - name: Update Helm repo index
        run: |
          helm repo index charts/ --url ${{ secrets.HELM_URL}}/main/charts

      - name: Commit and push changes to github helm repo
        run: |
          git clone https://${{ secrets.GPAT_TOKEN }}@github.com/jaypyles/helm-charts.git
          cd helm-charts
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          mkdir -p charts
          cp ../artifacts/* charts/
          git add charts/
          git commit -m "Add new dev-site chart version"
          git push origin main

      - name: Update version
        env:
          APP_VERSION: "${{ steps.vars.outputs.sha_short }}"
        run: |
          sed -i "s/APP_VERSION: .*/APP_VERSION: ${APP_VERSION}/g" charts/dev-site/values.yaml

      # - name: Commit changes
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     author_name: "github-actions"
      #     author_email: "github-actions@github.com"
      #     message: "Update version to ${{steps.vars.outputs.sha_short}} [skip ci]"
      #     add: "charts/dev-site/values.yaml"
